### ISSUE TITLE
GLPI 9.4.2 - working partially

### ISSUE THREAD

**Issue by Eon9D** [tomolimo/ticketcleaner#11] opened 2019-05-03 18:23 UTC
The plugin seems to work for tickets but not for followups anymore.

This might be due to "TicketFollowup" is deprecated and now "ITILFollowup".

**Comment by tomolimo** [comment] 2019-05-06 06:31
Oups!
Thank you for your report, I'll try to fix this asap. Or you may propose a Pull request?
Regards,
Tomolimo

**Comment by Eon9D** [comment] 2019-05-06 12:22
PR: Sorrry .. above my capabilities :/

**Comment by tomolimo** [comment] 2019-05-06 12:41
No problem, I'll check what I can do

**Comment by Eon9D** [comment] 2019-06-01 11:16
I would correct that from partially working to not working.

We have a strange issue with broken hyperlinks.
A link in a mail (https://abcdebay.com/) would be broken and will become like (http://glpi_of_company/front/;https://abcdebay.com/).
It took me a bit but after I disabled the ticketcleaner it worked!

Further investigation showed that is is an encoding problem??!

This gets handed to TicketCleaner
`
&lt;meta content=\"text/html; charset=us-ascii\" /&gt;&lt;meta content=\"Microsoft Word 14 (filtered medium)\" /&gt;&lt;div class=\"WordSection1\"&gt;&lt;p class=\"MsoNormal\"&gt;verlinkt zu sein:&lt;/p&gt;&lt;p class=\"MsoNormal\"&gt;&nbsp;&lt;/p&gt;&lt;p class=\"MsoNormal\"&gt;&lt;a href=\"https://abcdebay.com/\"&gt;https://abcdebay.com/&lt;/a&gt;&lt;/p&gt;&lt;p class=\"MsoNormal\"&gt;&nbsp;&lt;/p&gt;&lt;p class=\"MsoNormal\"&gt;&nbsp;&lt;/p&gt;&lt;/div&gt;
`
After the hook.php (Line 256) - encoding it becomes this
`
&lt;meta content=\&quot;text/html; charset=us-ascii\&quot; /&gt;&lt;meta content=\&quot;Microsoft Word 14 (filtered medium)\&quot; /&gt;&lt;div class=\&quot;WordSection1\&quot;&gt;&lt;p class=\&quot;MsoNormal\&quot;&gt;verlinkt zu sein:&lt;/p&gt;&lt;p class=\&quot;MsoNormal\&quot;&gt;&nbsp;&lt;/p&gt;&lt;p class=\&quot;MsoNormal\&quot;&gt;&lt;a href=\&quot;https://abcdebay.com/\&quot;&gt;https://abcdebay.com/&lt;/a&gt;&lt;/p&gt;&lt;p class=\&quot;MsoNormal\&quot;&gt;&nbsp;&lt;/p&gt;&lt;p class=\&quot;MsoNormal\&quot;&gt;&nbsp;&lt;/p&gt;&lt;/div&gt;
`
notice that `\"` became `\&quot;`

When I change from ENT_QUOTES to ENT_NOQUOTES it seems to work.
Do you agree with that so I can push to production?

**Comment by Eon9D** [comment] 2019-06-01 11:35
`--- html/helpdesk/plugins/ticketcleaner/setup.php	(date 1559388257000)
+++ html/helpdesk/plugins/ticketcleaner/setup.php	(date 1559388257000)
@@ -28,11 +28,11 @@
 
    $PLUGIN_HOOKS['pre_item_add']['ticketcleaner'] = array(
       	'Ticket' => array('PluginTicketCleaner', 'plugin_pre_item_add_ticketcleaner'),
-      	'TicketFollowup' => array('PluginTicketCleaner', 'plugin_pre_item_add_ticketcleaner_followup')
+      	'ITILFollowup' => array('PluginTicketCleaner', 'plugin_pre_item_add_ticketcleaner_followup')
       );
    $PLUGIN_HOOKS['pre_item_update']['ticketcleaner'] = array(
       	'Ticket' => array('PluginTicketCleaner', 'plugin_pre_item_update_ticketcleaner'),
-      	'TicketFollowup' => array('PluginTicketCleaner', 'plugin_pre_item_update_ticketcleaner_followup')
+      	'ITILFollowup' => array('PluginTicketCleaner', 'plugin_pre_item_update_ticketcleaner_followup')
       );
 
    $plugin = new Plugin();
`

That fixed the problem with the not processed followups for me.

**Comment by tomolimo** [comment] 2019-06-03 07:13
Hello @Eon9D 
Thank you for your tests and proposals, I'll check that, and keep you informed.
Regards,
Tomolimo

**Comment by Eon9D** [comment] 2019-06-23 08:52
Hey, I don't wanna annoy you but its been three weeks. Is there any update soon? Otherwise I am going to push into production.
Thanks

**Comment by tomolimo** [comment] 2019-06-24 09:40
Oups, sorry for being so late,
I'm going to check this during this week,
And I'll keep you informed,
Thank you

**Comment by tomolimo** [comment] 2019-06-28 13:54
Hello @Eon9D 
I totally agree for the change to ITILFollowup instead of TicketFollowup, but for the encoding problem, I need more time to be able to see exactly what's the root cause.
Thank you,
Tomolimo

**Comment by tomolimo** [comment] 2019-06-28 14:44
Hello @Eon9D ,

Here is what I propose to fix the issue of the single quote, double quotes, slashes and backslashes:

Replace the cleanText() function by the following one (in hook.php):


```
   public static function cleanText($parm) {
       global $DB;

       $is_content = array_key_exists('content', $parm->input);
       $is_name = array_key_exists('name', $parm->input);

      if ($is_content || $is_name) {
          // load filters from DB
          $filters = [ ];
          $query = "SELECT * FROM glpi_plugin_ticketcleaner_filters WHERE is_active=1 ORDER BY type, `order`;";

          // preparation for starts of filter
         foreach ($DB->request($query) as $filter) {
            $filters[ $filter['type'] ][] = $filter;
         }

         if ($is_content && isset($filters[ PluginTicketcleanerFilter::DESCRIPTION_TYPE ])) {
            // unsanitize doesn't exist...
            $temp_content = Toolbox::unclean_cross_side_scripting_deep($parm->input['content']);
            $temp_content = Toolbox::stripslashes_deep($temp_content);
            if (isset($_SESSION['glpi_use_mode']) && ($_SESSION['glpi_use_mode'] == Session::DEBUG_MODE)) {
                Toolbox::logInFile('TicketCleaner', "\tInitial text content: " . $temp_content . "\n" );
            }
            foreach ($filters[ PluginTicketcleanerFilter::DESCRIPTION_TYPE ] as $ptn) {
               $temp_content = preg_replace( $ptn['regex'], $ptn['replacement'], $temp_content );
               if (isset($_SESSION['glpi_use_mode']) && ($_SESSION['glpi_use_mode'] == Session::DEBUG_MODE)) {
                  Toolbox::logInFile('TicketCleaner', "\tAfter filter: " . $ptn['name'] . "\t text: " . $temp_content . "\n" );
               }
            }
            $temp_content = Toolbox::sanitize([$temp_content]);
            $parm->input['content'] = $temp_content[0];
         }

         if ($is_name && isset($filters[ PluginTicketcleanerFilter::TITLE_TYPE ])) {
            foreach ($filters[ PluginTicketcleanerFilter::TITLE_TYPE ] as $ptn) {
                $parm->input['name'] = preg_replace( $ptn['regex'], $ptn['replacement'], $parm->input['name'] );
            }
         }

      }
   }

```
And keep me informed of your tests.

Thank you
Regards,
Tomolimo

**Comment by Eon9D** [comment] 2019-06-29 15:03
Okay. Is this tested? I would put this into production then as I have no way of testing it in an dev system.

**Comment by tomolimo** [comment] 2019-07-01 07:32
Hello @Eon9D 
I made some tests, but there is no guarantee that it fits your needs...
You must do your own tests before doing this update on production server.
Anyway, here are the tests I made:

#### source:
> test <- ah ah
> Here a single ', here is Marc's car
> two single quotes '', here is a string: 'Marc's car is black'.
> a double ": "Marc's car is red" (color is changing :) )!
> two doubles "": ""
> slashes https://github.com/tomolimo/ticketcleaner
> backslashes in UNC path:  \\10.10.0.120\l$\sources\glpi9.1.2
 
#### result when creating a ticket via web interface:

> test ⇦ ah ah
> 
> Here a single ', here is Marc's car
> 
> two single quotes '', here is a string: 'Marc's car is black'.
> 
> a double ": "Marc's car is red" (color is changing :) )!
> 
> two doubles "": "with a text within double quotes"
> 
> slashes https://github.com/tomolimo/ticketcleaner
> 
> backslashes in UNC path:  <\\10.10.0.120\l$\sources\glpi9.1.2>

there is a rule that convert <- into ⇦
This result is OK

#### result when creating a ticket via email (my email application is Outlook):

> test <- ah ah
> 
> Here a single ', here is Marc's car
> 
> two single quotes '', here is a string: 'Marc's car is black'.
> 
> a double ';: ';Marc's car is red'; (color is changing :) )!
> 
> two doubles ';';: ';';
> 
> slashes https://github.com/tomolimo/ticketcleaner
> 
> backslashes in UNC path:  \\10.10.0.120\l$\sources\glpi9.1.2

<- is not correct
double quotes are not correct, and are converted to single quotes+semi-columns
This result is not OK,

I'll check that, and keep you informed,

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2019-07-01 12:24
Hello @Eon9D 
After some searches I saw that the semi-column issue is from GLPI: see this PR: https://github.com/glpi-project/glpi/pull/6084
I'm still investigating on the " (quote) transformed into ' (amp)

**Comment by tomolimo** [comment] 2019-07-01 12:46
And I can see also that the transformation of the " into the ' is also due to GLPI: see https://github.com/glpi-project/glpi/pull/6084 
I sent one PR to fix these issues.

**Comment by tomolimo** [comment] 2019-07-02 14:37
Fixed by https://github.com/tomolimo/ticketcleaner/releases/tag/2.5.0

**Closed by tomolimo** 2019-07-02 14:37 UTC
Labels: bug
